version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.3

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Installing prototool
          command: |
            sudo wget -O /usr/local/bin/prototool https://github.com/uber/prototool/releases/download/v0.6.0/prototool-$(uname -s)-$(uname -m) && \
              sudo chmod +x /usr/local/bin/prototool

      - run:
          name: Running tests
          command: make test
